### ISSUE TITLE
arrow-bci-schedule-and-publish: TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by austin3dickey** [voltrondata-labs/arrow-benchmarks-ci#117]
The schedule-and-publish job currently is throwing many errors every time it executes. These look to be because the client is expecting a different Conbench API schema than what actually is deployed for Arrow Conbench today.

https://buildkite.com/apache-arrow/arrow-bci-schedule-and-publish/builds/43885#01886d35-97d3-4e2a-9e50-1dbb951effc0/116-131
```
Traceback (most recent call last):
  File "/app/buildkite/schedule_and_publish/publish_benchmark_results_on_slack.py", line 19, in publish_benchmark_results_on_slack
    text = notification.generate_slack_message_text()
  File "/app/models/notification.py", line 118, in generate_slack_message_text
    + self.generate_comment_with_compare_runs_links()
  File "/app/models/notification.py", line 63, in generate_comment_with_compare_runs_links
    url = self.benchmarkable.conbench_compare_runs_web_url(machine)
  File "/app/models/benchmarkable.py", line 169, in conbench_compare_runs_web_url
    baseline_run_id = self.baseline_machine_run(machine).id
AttributeError: 'NoneType' object has no attribute 'id'
```

https://buildkite.com/apache-arrow/arrow-bci-schedule-and-publish/builds/43885#01886d35-97d3-4e2a-9e50-1dbb951effc0/116-152
```
Traceback (most recent call last):
  File "/app/buildkite/schedule_and_publish/publish_benchmark_results_on_slack.py", line 19, in publish_benchmark_results_on_slack
    text = notification.generate_slack_message_text()
  File "/app/models/notification.py", line 118, in generate_slack_message_text
    + self.generate_comment_with_compare_runs_links()
  File "/app/models/notification.py", line 62, in generate_comment_with_compare_runs_links
    status = self.benchmarkable.machine_runs_status(machine)
  File "/app/models/benchmarkable.py", line 204, in machine_runs_status
    raise e
  File "/app/models/benchmarkable.py", line 185, in machine_runs_status
    regressions, improvements = self.regressions_and_improvements(machine)
  File "/app/models/benchmarkable.py", line 253, in regressions_and_improvements
    [
  File "/app/models/benchmarkable.py", line 256, in <listcomp>
    if r["analysis"]["lookback_z_score"]["regression_indicated"]
TypeError: 'NoneType' object is not subscriptable
```

These are repeated a few times per build.

**Comment by alistaire47** [comment]
This is because abci is now ahead of what's deployed because we deployed, updated in #114, then rolled back the deployment. This could be solved by rolling back #114 or just deploying again. If we roll it back, we'll need to roll it forward again after we eventually deploy again.

**Comment by austin3dickey** [comment]
As I mentioned [here](https://github.com/voltrondata-labs/arrow-benchmarks-ci/issues/118#issuecomment-1568880163), the Arrow Conbench HTTP API should be using the latest schema available right now. I'm a little confused where the mismatch is. I haven't looked into it too much yet.

**Comment by alistaire47** [comment]
Oh crap, is this because the contender or baseline is missing for a result? We might need to do 

``` python
(r["analysis"].get("lookback_z_score") or {}).get(regression_indicated)
```
or similar

**Comment by alistaire47** [comment]
Ah yeah here's what benchalerts has now

https://github.com/conbench/conbench/blob/81a0272cc28c8bd10d3f993d58c0f63efbff8f02/benchalerts/benchalerts/conbench_dataclasses.py#L75-L79

``` python
                    has_z_regression=comparison["analysis"]["lookback_z_score"][
                        "regression_indicated"
                    ]
                    if comparison["analysis"]["lookback_z_score"]
                    else False,
```
I'll put together a PR

**Comment by alistaire47** [comment]
The PR closed this and it's probably fixed, but let's keep an eye on it and reopen if that was in fact not the problem

**Comment by austin3dickey** [comment]
Nice, that error went away: https://buildkite.com/apache-arrow/arrow-bci-schedule-and-publish/builds/43909#01886e12-a423-4cb6-984e-85036a3cec7f

The first error still shows up, though: 
```
  File "/app/models/benchmarkable.py", line 169, in conbench_compare_runs_web_url
    baseline_run_id = self.baseline_machine_run(machine).id
AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by alistaire47** [comment]
Hmm, this is a different issue; I think we're now somehow violating an assumption which was previously true. You can see in this code how it assumes that one of the machines will match:

https://github.com/voltrondata-labs/arrow-benchmarks-ci/blob/ad5e8b2ce28a35e6786e02491d7a523787f51256/models/benchmarkable.py#L158-L171

The only reason I can think of that would be false is if a run failed on that machine on the parent and it needs to skip that commit to find a matching run.

**Comment by austin3dickey** [comment]
I see; this doesn't really have to do with the API schema but is a separate bug. Its scope is probably just limited to one run comparison, and then the code moves onward. (This is probably the same code that causes the `SAWarning` down below but the logs are mixed up.) Will open another issue.

**Comment by jgehrcke** [comment]
I changed the title to reflect the specific problem that I think this issue is/was supposed to track.

**Comment by jgehrcke** [comment]
I am seeing
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/app/buildkite/schedule_and_publish/publish_benchmark_alerts_on_pull_requests.py", line 22, in publish_benchmark_alerts_on_pull_requests
    notification.generate_pull_comment_body_for_high_regression_alert(
  File "/app/models/notification.py", line 97, in generate_pull_comment_body_for_high_regression_alert
    runs = self.benchmarkable.runs_with_high_regressions(benchmark_langs_filter, benchmark_machine_ignorelist)
  File "/app/models/benchmarkable.py", line 298, in runs_with_high_regressions
    results = [
  File "/app/models/benchmarkable.py", line 301, in <listcomp>
    if r["contender"]["language"] in benchmark_langs_filter
TypeError: 'NoneType' object is not subscriptable
ERROR: 1
🚨 Error: The command exited with status 1
```
(https://buildkite.com/apache-arrow/arrow-bci-schedule-and-publish/builds/43992#0188710c-69ad-4116-bf84-ca7a7d8f6048/116-127)

Re-opening this. It's a slightly different code error, but I think we can think of this ticket so that it is about those dictionary lookups where the dict obj is `None`.

**Comment by jgehrcke** [comment]
Seeing a bunch of `"contender":null` in e.g. https://conbench.ursa.dev/api/compare/runs/814764d1467841c990c10c0e4f2b24a7...c184cde129074c5fb0bd94c040c2fb06/.

Quick patch attempt: https://github.com/voltrondata-labs/arrow-benchmarks-ci/pull/123

**Comment by austin3dickey** [comment]
I don't see any more tracebacks related to dictionary lookups where the dict obj is None. Calling this done.
