### ISSUE TITLE
schedule-and-publish job is timing out every time

### ISSUE THREAD

**Issue by austin3dickey** [voltrondata-labs/arrow-benchmarks-ci#118]
Currently the `arrow-bci-schedule-and-publish` Buildkite job is scheduled to run every 10 minutes. If it runs for longer than 10 minutes, it is canceled. Today, this is happening every time the job runs:
<img width="1109" alt="image" src="https://github.com/voltrondata-labs/arrow-benchmarks-ci/assets/16600275/e740a83e-972a-45bd-b2b6-47030223e4b0">

This has the side effect that these later steps have not run in a long time:
<img width="1181" alt="image" src="https://github.com/voltrondata-labs/arrow-benchmarks-ci/assets/16600275/fe1975e0-c7ae-4803-87bf-97d274a28f3c">

Today each job is being canceled during the "Publish Benchmark Results On Slack" step. In [this build](https://buildkite.com/apache-arrow/arrow-bci-schedule-and-publish/builds/43886#01886d3f-a03c-4056-b818-f20ebe7cef5e), for example, the code was able to hit `GET https://conbench.ursa.dev/api/compare/runs/BID...CID` for 29 different comparisons before timing out after about 8 minutes. It was never able to post anything to Slack. It's unclear how many total comparisons it was trying to get the information for.

**Comment by alistaire47** [comment]
> It's unclear how many total comparisons it was trying to get the information for.

We should log this in benchalerts

**Comment by austin3dickey** [comment]
I believe benchalerts does log this, but we haven't implemented benchalerts in this repo yet (see #98).

I just connected to the database, and here are the current numbers of unsent notifications:

```
postgres=> select type, count(*) from notification where finished_at is null group by type;
        type        | count
--------------------+-------
 pull_comment       |    72
 pull_comment_alert |    56
 slack_message      |    81
```

It does look like a big backlog.

**Comment by austin3dickey** [comment]
A hunch: perhaps we could first straighten out #116 and #117, and then manually run one of these jobs as an asynchronous backfill, without a timeout. Then we'd have no more backlog on subsequent runs. I think the Conbench API is fast enough for this job to be stable again if we don't have a backlog.

**Comment by alistaire47** [comment]
> I believe benchalerts does log this, but we haven't implemented benchalerts in this repo yet (see #98).

Oops, undercaffeinated, sorry.

> manually run one of these jobs as an asynchronous backfill, without a timeout.

Would changing the cron schedule to once an hour or something have the same effect without having to set up a separate run?

> I think the Conbench API is fast enough for this job to be stable again if we don't have a backlog.

It is right now in the rolled-back version; if we deploy again I'm less certain since that's how we got in this situation. Making it run less frequently might be enough? But we also need to address issues like the OOMs which may (?) have been contributing to the compare slowness.

**Comment by austin3dickey** [comment]
>Would changing the cron schedule to once an hour or something have the same effect without having to set up a separate run?

It might? But to me, kicking off a manual BK job seems a little easier. (Famous last words.) We want to keep a relatively high-frequency cron on this job because we don't want too much notification latency in general.

>the rolled-back version

We didn't roll back too far; the last deployment to Arrow Conbench is this, seen at the bottom of the webapp:
<img width="288" alt="image" src="https://github.com/voltrondata-labs/arrow-benchmarks-ci/assets/16600275/46720c4d-7dbe-427e-afcb-da78bd8c8bc0">

https://github.com/conbench/conbench/commit/2f8a2b0a9

As of writing, that's only 3 commits behind the HEAD of `main`. The API code wasn't changed in those 3 commits, so we're still using pretty much the latest code.

**Comment by jgehrcke** [comment]
Improved a bit after https://github.com/voltrondata-labs/arrow-benchmarks-ci/pull/123:
![image](https://github.com/voltrondata-labs/arrow-benchmarks-ci/assets/265630/5e16b60a-5715-4d22-a932-ef495777a095)

Not timing out anymore. But there are still crashes, seemingly (the green color is misleading): https://github.com/voltrondata-labs/arrow-benchmarks-ci/issues/120#issuecomment-1569969313

**Comment by austin3dickey** [comment]
I think this is actually done! With the small bugfixes we've made in the last 24 hours, and the fact that Arrow development slowed down overnight, this pipeline was able to get through its backlog.

In the medium term: switching to `benchalerts` (#98) will definitely help this pipeline go faster. Looking at the logs, today we hit `/api/compare/runs` four different times for every Conbench run. That endpoint is currently a little slow (see https://github.com/conbench/conbench/issues/1283). `benchalerts` will only hit that endpoint once per run.

**Comment by jgehrcke** [comment]
Nice!

**Comment by austin3dickey** [comment]
Note that we still sometimes get a small backlog of jobs that can't be completed within 10 minutes. But since the job is idempotent, it always resolves itself within a few tries. Again, I think the frequency of this issue will decrease once we do #98.

<img width="260" alt="image" src="https://github.com/voltrondata-labs/arrow-benchmarks-ci/assets/16600275/da2ef1e0-7428-4bec-888e-e55ee2a4106c">
