### ISSUE TITLE
schedule-and-publish job: error when a Benchmarkable is missing baseline (`'NoneType' object has no attribute 'id'`), non-fatal

### ISSUE THREAD

**Issue by austin3dickey** [voltrondata-labs/arrow-benchmarks-ci#120]
https://github.com/voltrondata-labs/arrow-benchmarks-ci/issues/117#issuecomment-1568970121

It's very possible for this code to never return a "run", so it returns None:

https://github.com/voltrondata-labs/arrow-benchmarks-ci/blob/ad5e8b2ce28a35e6786e02491d7a523787f51256/models/benchmarkable.py#L163-L166

This breaks this line:

https://github.com/voltrondata-labs/arrow-benchmarks-ci/blob/ad5e8b2ce28a35e6786e02491d7a523787f51256/models/benchmarkable.py#L169

which results in [this error](https://buildkite.com/apache-arrow/arrow-bci-schedule-and-publish/builds/43909#01886e12-a423-4cb6-984e-85036a3cec7f/118-133). This happens for one run comparison every time we run a schedule-and-publish job. It's unclear to me if the scope is bigger than that.

**Comment by alistaire47** [comment]
I looked into this previously think it might still be failing on this run? Or another in the same situation https://github.com/conbench/conbench/issues/1283#issuecomment-1563557989

**Comment by jgehrcke** [comment]
Error looks like this:
```
WARNING: The MACHINES_WITH_FAILED_BUILDS variable is not set. Defaulting to a blank string.
Creating prod_app_run ... done
[2023-05-31 10:52:34,070] ERROR in publish_benchmark_results_on_slack: 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/app/buildkite/schedule_and_publish/publish_benchmark_results_on_slack.py", line 19, in publish_benchmark_results_on_slack
    text = notification.generate_slack_message_text()
  File "/app/models/notification.py", line 118, in generate_slack_message_text
    + self.generate_comment_with_compare_runs_links()
  File "/app/models/notification.py", line 63, in generate_comment_with_compare_runs_links
    url = self.benchmarkable.conbench_compare_runs_web_url(machine)
  File "/app/models/benchmarkable.py", line 169, in conbench_compare_runs_web_url
    baseline_run_id = self.baseline_machine_run(machine).id
AttributeError: 'NoneType' object has no attribute 'id'
/app/models/base.py:46: SAWarning: fully NULL primary key identity cannot load any object.  This condition may raise an error in a future release.
  return Session().get(cls, _id)
```
Interesting: it's not failing the build step.

**Comment by austin3dickey** [comment]
#126 did get rid of this issue. https://buildkite.com/apache-arrow/arrow-bci-schedule-and-publish/builds/44049#01887314-5034-419f-8f12-d12fb7eb6642/118-125
