### ISSUE TITLE
benchmarking pipelines: high failure rate of R TPCH benchmarks

### ISSUE THREAD

**Issue by jgehrcke** [voltrondata-labs/arrow-benchmarks-ci#131]
We have a high build failure rate across benchmarking-related pipelines in  https://buildkite.com/apache-arrow:

![image](https://github.com/voltrondata-labs/arrow-benchmarks-ci/assets/265630/91406964-5d82-4b0a-97a5-a4a2acb3466c)

Right now many (all?) of the build failures shown in the screenshot above are as of https://github.com/apache/arrow/issues/35917

High-level symptom towards the end of each build log:

```
FAILED R tpch 0
...

  File "/var/lib/buildkite-agent/builds/aws-ec2-m5-4xlarge-us-east-2-i-0a69a796456df1443-1/apache-arrow/arrow-bci-benchmark-on-ec2-m5-4xlarge-us-east-2/buildkite/benchmark/run_benchmark_groups.py", line 10, in run_benchmark_groups
    run.run_all_benchmark_groups()
  File "/var/lib/buildkite-agent/builds/aws-ec2-m5-4xlarge-us-east-2-i-0a69a796456df1443-1/apache-arrow/arrow-bci-benchmark-on-ec2-m5-4xlarge-us-east-2/buildkite/benchmark/run.py", line 695, in run_all_benchmark_groups
    raise Exception("Build has failed benchmarks.")
Exception: Build has failed benchmarks.
```

More details in https://github.com/apache/arrow/issues/35917.

Example build logs:

https://buildkite.com/apache-arrow/arrow-bci-benchmark-on-ec2-m5-4xlarge-us-east-2/builds/2369#018898e4-9321-470f-834e-8336abcd2ab0/6-12673

https://buildkite.com/apache-arrow/arrow-bci-benchmark-on-arm64-m6g-linux-compute/builds/2824#0188992a-c390-4759-8e65-582c43f51714/6-12645

**Comment by jgehrcke** [comment]
@jonkeane helped via https://github.com/voltrondata-labs/arrowbench/pull/136 and we see improvement:

![image](https://github.com/voltrondata-labs/arrow-benchmarks-ci/assets/265630/05c98df3-fa98-48dc-b9c3-197f119150b4)

The `Arrow BCI Benchmark on arm64-t4g-linux-compute` pipeline still fails, there is a symptom I had not seen before. now tracking here: https://github.com/voltrondata-labs/arrow-benchmarks-ci/issues/133

**Comment by jgehrcke** [comment]
And another symptom: https://github.com/voltrondata-labs/arrow-benchmarks-ci/issues/135

**Comment by austin3dickey** [comment]
All builds are consistently green now. I think we can count this "complete" (and use the open linked tickets for the transient issues if they appear again).
