### ISSUE TITLE
Stop benchalerts from alerting on test-mac-arm and languages other than Python/R

### ISSUE THREAD

**Issue by austin3dickey** [voltrondata-labs/arrow-benchmarks-ci#142]
We used to not alert in those cases, but #132 turned them back on again. Stop them.

Relates to https://github.com/conbench/conbench/issues/475

**Comment by alistaire47** [comment]
We should really make a plan for the future of alerting for cases we're not alerting on—if we're not telling anyone when they fail, why are we running them? (There's still some value to seeing when they fail, but that's just more testing, not actual benchmarking for regressions.) Is turning alerting on pending improvements in data quality? Do we need to talk with Arrow devs to make a plan for these? 

Whatever the plan, we should have an issue for it. I'm happy to open one, though if someone else has more preexisting context for the situation, they could lay out the situation better.

**Comment by austin3dickey** [comment]
The original rationale for turning off test-mac-arm alerts was here: https://github.com/voltrondata-labs/arrow-benchmarks-ci/pull/109

Agreed that we should have a plan for reducing noise in these benchmarks that leads to turning the alerts back on. A big-impact solution here could be https://github.com/conbench/conbench/issues/635.
